name: expense_planner
description: expense planner

publish_to: 'none'
version: 1.0.0

environment:
    sdk: ">=2.7.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    intl: ^0.16.1
    cupertino_icons: ^1.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
